#!/bin/bash
# CMake 4.0 dropped support for cmake_minimum_required < 3.5.
# Only inject -DCMAKE_POLICY_VERSION_MINIMUM=3.5 in configure mode.
# Non-configure modes (--build, --install, -E, etc.) reject -D flags.
for arg in "$@"; do
    case "${arg}" in
        --build|--install|--open|-E|--workflow|--version|--help|-h)
            exec /usr/bin/cmake "$@"
            ;;
    esac
done
exec /usr/bin/cmake -DCMAKE_POLICY_VERSION_MINIMUM=3.5 "$@"
